# Generated by Django 3.1.1 on 2020-09-16 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidates', '0002_auto_20200915_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='assignedto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
